sudo: required
language: go
go:
- 1.10.x
services:
- docker
branches:
  only:
  - master
before_script:
- export TAG=`if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master"
  ]]; then echo "latest"; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi`
before_install:
- go get -u github.com/golang/dep/...
- dep ensure
script:
- go test ./... -coverprofile=coverage.txt -covermode=atomic
- docker build -t $REPO:$TAG -f Dockerfile .
after_success:
- bash <(curl -s https://codecov.io/bash)  || echo "Codecov did not collect coverage
  reports"
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ $TRAVIS_BRANCH == "master" ]]; then
  docker tag $REPO:$TAG $REPO:$TRAVIS_BUILD_NUMBER; docker push $REPO:$TRAVIS_BUILD_NUMBER;
  fi
- docker push $REPO:$TAG
